logging:
  level:
    org.apache.coyote.http11: debug

spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 1000MB
      enabled: true # multi part enable

file.dir: ${filePath}
